### PR TITLE
Added build directory

### PR DESCRIPTION
**Pull request by stheno**
Added ability to have differentiation between different desktop arch and versions allowing multiples on one iso. Dropped server implementation from previous PR. Will look at that later.

### CODE REVIEW

**Comment by IsaacSchemm** [comment]
In the EDITS section, why do you have \\t instead of \t? I'm ending up with actual "\t"s in my file. When I change it to \t in EDITS, I get tabs and it works.

Other than that, it looks good. I'll make the changes to the -o option in another branch first, and then merge this one when I'm done.

**Comment by IsaacSchemm** [comment]
The plugin still seems to pick up on the server ISO and add a menu entry for it that doesn't go anywhere. Could you look into that?

The "back to main menu" link is also not working, but I think that would be an easy fix.

**Comment by stheno** [comment]
Yep, I just noticed it and have been working on that.
Weird on the tab issue. I have not run across that issue.
I'll try to duplicate it before I commit this last fix.

**Comment by stheno** [comment]
Ok I was not able to duplicate what so ever the issue with tabs.
Server bit fixed tho.

**Comment by IsaacSchemm** [comment]
I was testing it on Cygwin. That could be part of the issue.

**Comment by stheno** [comment]
Ah yea. I am testing from vbox

**Comment by IsaacSchemm** [comment]
I found the root of the tabs issue. Cygwin's default /bin/sh is bash, which exhibits the problem I described; Ubuntu's is dash, which doesn't. I'm thinking I'll just avoid the issue by replacing those tabs with spaces, if that's OK with you.

**Comment by stheno** [comment]
Sounds good, I was thinking that may need to happen for compatibility across systems.

**Comment by stheno** [comment]
I don't know anything about cygwin. but can it be forced to use dash? Maybe avoid weird cross language issues in general?

**Comment by IsaacSchemm** [comment]
Cygwin does come with dash (/usr/bin/dash), so just changing the first line of ubuntu.sh should fix it. However, this will make the plugin not work if dash isn't installed. I'm not sure how widespread dash is - e.g. whether Fedora or FreeBSD come with it.

**Comment by stheno** [comment]
good point. Spaces it is :-) I'll put those in my PR

**Comment by stheno** [comment]
Ok fixed spaces. All should be good to go now?

**Comment by stheno** [comment]
I may as well ask this then...
Why use bin/sh instead of bin/bash in the files then?
I was actually trying to make sure it was dash compat thinking sh meant dash not bash
Genuine question as I have not looked through all the code of the whole project to see if that would be answered by looking.

**Comment by IsaacSchemm** [comment]
Most of the code works in either one. I think this is the first time 
I've found something that works in dash but not in bash.

stheno wrote:

**Comment by stheno** [comment]
Once you approve and merge this I have a iso downloader I am working on too

**Pull request merged**
