### PR TITLE
Implemented ISO downloader

### PR DESCRIPTION
**Pull request by stheno**
Only the Ubuntu is populated but the template and comments are there for any others to be added.

### CODE REVIEW

**Comment by IsaacSchemm** [comment]
I get some errors when I press cancel on the list of Ubuntu ISOs:

    /home/isaac/multicd/downloader.sh: line 98: [: =: unary operator expected
    /home/isaac/multicd/downloader.sh: line 101: [: =: unary operator expected
    [3;J
    Downloading 12.04.5 Alternate 32bit...
    No such file or directory
    Error: could not download . Please update the URL in downloader.sh.

Otherwise it looks pretty good. It even stopped me and told me to install dialog first, which is good, because I did need to.

**Comment by stheno** [comment]
This is under cygwin? I went to that exact iso selection and hit cancel on a Ubuntu 14.04 system and did not get the unary errors.

**Comment by IsaacSchemm** [comment]
This time its on ubuntu. Haven't tried cygwin yet.

**Comment by stheno** [comment]
I found it, needed a double bracket. I have to create a special exit state to spot it.

**Pull request merged**
